### ISSUE TITLE
EagleCrestLogger - Naming Conventions and Spacing in logGuestEntry

### ISSUE THREAD

**Issue by liaaannnneee** [nchjhy/9472-Team01_Swift_FinalProject#14]
The print statement's lack of a space after the "ID" label and the function's excessively long variable name uniqueGuestID make it difficult to comprehend. A more readable and consistent name for the list logEntries would also be beneficial.

**Comment by JerilynLouise** [comment]
fixed the issue. Renamed uniqueGuestID to guestID, updated the list name to entryLog, and formatted the print statement for clarity.
