### ISSUE TITLE
EagleCrestLogger - Input Validation in logResidentEntry

### ISSUE THREAD

**Issue by liaaannnneee** [nchjhy/9472-Team01_Swift_FinalProject#15]
The input validation is unclear when processing empty input and use a badly structured trimmingCharacters technique. Additionally, it capitalizes ".whitespacesandNewlines" incorrectly.

**Comment by chloecsm** [comment]
Good day, I have properly trimmed the input, checked for non-empty strings, and updated the logResidentEntry function in EagleCrestLogger.swift for better readability and error handling.
