### ISSUE TITLE
EagleCrestLogger - Lack of Validation for User Input 

### ISSUE THREAD

**Issue by liaaannnneee** [nchjhy/9472-Team01_Swift_FinalProject#4]
User input for incorrect or distorted resident IDs—such as empty strings or excessive length—is not validated by the application. It is necessary to include validation.

**Comment by chloecsm** [comment]
Good day, Ms. Abitan. I’ve already addressed the issue with user input validation for resident IDs. The necessary measures to handle empty strings, excessively long inputs, and other invalid entries have been implemented. Let me know if you need anything further on this.
