### ISSUE TITLE
Incorrect Usage of TipCalculatorHelper

### ISSUE THREAD

**Issue by JerilynLouise** [nchjhy/9472-Team01_Swift_FinalProject#9]
The helper variable is initialized as TipCalculatorHelper, but it is not defined in the code. This will cause a compilation error. Either replace the helper with a Calculation struct instance or give the right helper implementation.

**Comment by chloecsm** [comment]
Thank you for pointing this out. I'll analyze the code and try to fix the problem by replacing the helper with a Calculation struct instance or implementing the correct helper.

**Comment by chloecsm** [comment]
I resolved the issue by replacing the TipCalculatorHelper with the Calculation struct. This should fix the compilation error. Let me know if you have any more queries or need anything else addressed.
